### ISSUE TITLE
Possibility to use for API

### ISSUE THREAD

**Issue by tomasharkema** [acouvreur/traefik-ondemand-plugin#13]
Thanks for this great plugin! I'd like to have an option for an API to just delay the request till the container has been started. Now it will respond with HTML which is not nice for an JSON api. Is this something that is remotely implementable? I'd like to hear!

**Comment by acouvreur** [comment]
Yes see https://github.com/acouvreur/traefik-ondemand-plugin/pull/12 with blocking strategy.
You can checkout the branch to try it out

**Comment by tomasharkema** [comment]
Ah great thanks! Do you maybe have some directions on how to use a branch in the Traefik configuration? Or is it only possible via localPlugins? Thanks!
