### ISSUE TITLE
Scale down/up multiple containers with one middleware

### ISSUE THREAD

**Issue by Nastaliss** [acouvreur/traefik-ondemand-plugin#19]
Hi and thank you for developing this plugin ! 
I tested it on my infrastructure and it works perfectly. However some of the apps I want to scale down / up are composed of up to 10 Kubernetes deployments. This makes scaling up painfully slow as some of them take some time to start, and having 10 middlewares means the deployments start one by one. 
Having so many deployments also makes managing all the middlewares finicky. 
I've started working on a modification on this plugin to take multiple resources as an input.
I'll keep you posted on my progress.

**Comment by Nastaliss** [comment]
Hey @khalid244 thanks for your feedback on this! 
I'm currently away but I'll take a look when I get back.

**Comment by khalid244** [comment]
Thank you very much!
It is working very well now.
