### ISSUE TITLE
Ability To Add Dynamic Loading

### ISSUE THREAD

**Issue by JeffResc** [acouvreur/traefik-ondemand-plugin#2]
First off, I think that this plugin is great and I'd love to use it in "production", but the only thing stopping me is that I don't like that it requires an extra step on the user's end (the refresh).

I would like to propose the following two options to see if either is available or is even possible with a setup like this:

1.) Do not load a page until the underlying service is available. I would almost prefer this than having another step for the user, but depending on the startup time, the user may think that the server might not reply and get impatient. Therefore, I'm not sure if this is a great solution.

2.) I would much rather prefer this solution. Say you have one container that stays on continuously in order to serve a static page. This same container can be used across all services that implement this on demand service. On this webpage, it would have a loading animation almost similar to Cloudflare's ["checking your browser"](https://images.ctfassets.net/slt3lc6tev37/55EYMR81XJCIG5uxLjQQOx/252a98adf90fa0ff2f70437cc5c0a3af/under-attack-mode_enabled.gif) page. Then, there could be some simple JavaScript that can detect if the real web server is up and automatically refresh the page for the user once it is.

With that said, I understand this is a lot for a community open-source project and I understand if this just isn't possible, but I just wanted to share my thoughts on this as I think it's already a really great idea.

Thanks!

**Comment by acouvreur** [comment]
Done this in PR #5 

![ondemand gif](https://user-images.githubusercontent.com/22034450/134826067-5aab6972-f10c-4434-8936-350dd9b7ba8f.gif)

Feedback appreciated
