### ISSUE TITLE
Error: plugin: unknown plugin type: traefik-ondemand-plugin

### ISSUE THREAD

**Issue by Pixelartist** [acouvreur/traefik-ondemand-plugin#26]
Hello there,

I am trying to play and understand this plugin and tried to run the example for classic docker. Given that the readme already lead to errors I just simply started the docker-compose and it leads to the following error:

> level=error msg="plugin: unknown plugin type: traefik-ondemand-plugin" entryPointName=http routerName=whoami@file

I raised the version to 1.2.0 and am trying to understand how to load the plugin correctly but any help would be greatly appreciated.

**Comment by acouvreur** [comment]
What is your traefik configuration ?
It seems that you didnt correctly provide a traefik pilot token or you did not import the middleware.

**Comment by Pixelartist** [comment]
That was quick - I did not set any traefik pilot token (if I remember correctly it stated that it defaults to null), maybe this is exactly where me misunderstanding comes from. Does it need a necessarily need a token? I understood the pilot as "optional" services.

`version: "3.9"

services:
  traefik:
    image: traefik
    command:
      - --api=true
      - --api.insecure=true
      - --pilot.token=$TRAEFIK_PILOT_TOKEN
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
      - --experimental.plugins.traefik-ondemand-plugin.version=v1.2.0
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic-config.yml
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './dynamic-config.yml:/etc/traefik/dynamic-config.yml'
    labels:
      - traefik.enable=true

  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:1
    command: 
      - --swarmMode=false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.name=docker_classic_whoami_1
      - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000
      - traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.timeout=1m
      - traefik.http.services.ondemand.loadbalancer.server.port=10000

  whoami:
    image: containous/whoami
    # Cannot use labels because as soon as the container is stopped, the labels are not treated by Traefik
    # The route doesn't exist anymore. Use dynamic-config.yml file instead.
    # labels:
    #  - traefik.enable
    #  - traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)
    #  - traefik.http.routers.whoami.middlewares=ondemand`

**Comment by acouvreur** [comment]
You do need a token.

If you go to the official website and click install on this plugin it shows you the steps to follow https://pilot.traefik.io/plugins/605afbdba5f67ab9a1b0e53a/containers-on-demand

![image](https://user-images.githubusercontent.com/22034450/166568464-080d52e5-9861-4d0a-9f0d-65abac3916fc.png)

So you need to register your instance, which means set a token value
