### ISSUE TITLE
Feature Request: option to block request until container loads

### ISSUE THREAD

**Issue by jimcortez** [acouvreur/traefik-ondemand-plugin#7]
Thank you for this cool idea! I am hoping to use it to reduce the load on a server that has a few rarely-used containers.

It would be great to have a feature that simply keeps the request open until the container is up and running, without a loading screen.

A great use case for this is a simple container I run that serves a single json file (a .wellknown file). If I put the ondemand plugin on this, it would break clients as they don't know how to parse the loading screen. However, if it simply blocked until the container is up and running, it would work.

An additional parameter for "wait" time after a container starts may be necessary if it takes some time for the container to be ready to serve an image.

**Comment by acouvreur** [comment]
Thanks for this idea, I like it to be honest !

I mainly designed this plugin for end-users, but I see that it could also be used to load up APIs, backend...

Do you have any suggestion about the configuration update ?

```diff
testData:
  serviceUrl: http://ondemand:10000
  name: TRAEFIK_HACKATHON_whoami
  timeout: 1m
+ dynamic: false
+  wait: 30s
```

To me `timeout` and `wait` will be confusing.

**Comment by jimcortez** [comment]
maybe

```
testData:
  serviceUrl: http://ondemand:10000
  name: TRAEFIK_HACKATHON_whoami
  timeout: 1m
+ wait-ui: false
+ block-delay: 30s```

Another option would to just deny the request and then we could chain ondemand with a retry middleware.
